name: PR Checks

on:
  pull_request:
    branches: [ main ]
    types: [ opened, synchronize, reopened, ready_for_review ]
  push:
    branches: [ main ]
    paths-ignore:
    - 'README.md'
    - 'docs/**'
    - '.github/workflows/**'
  workflow_dispatch:


permissions:
  contents: read
  pull-requests: write
  checks: write
  security-events: write

jobs:
  test:
    runs-on: ubuntu-latest
    if: ${{ !github.event.pull_request.draft }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v3
      with:
        languages: javascript
        config-file: ./.github/codeql/codeql-config.yml
        queries: +security-and-quality

    - name: Run CI pipeline
      run: npm run ci:full

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3
      with:
        category: "/language:javascript"

    - name: Upload coverage
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: coverage/

    - name: Build production
      run: npm run build:prod

    - name: Comment on PR
      if: always()
      uses: actions/github-script@v7
      with:
        script: |
          const fs = require('fs');
          const path = require('path');

          // Check if coverage directory exists
          let coverageInfo = '';
          try {
            if (fs.existsSync('coverage/ztmm-assessment/index.html')) {
              coverageInfo = '📊 Code coverage report generated and uploaded as artifact.';
            }
          } catch (e) {
            coverageInfo = '⚠️ Coverage report not found.';
          }

          const comment = `## ✅ Pull Request Checks Complete

          All required checks have passed:
          - ✅ Code Quality (Linting & Type Checking)
          - ✅ Unit Tests with Coverage
          - ✅ Security Tests (All security test suites)
          - ✅ Dependency Security Audit
          - ✅ CodeQL Security Analysis
          - ✅ Production Build

          ${coverageInfo}

          🚀 This PR is ready for review!
          `;

          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: comment
          });
